### ISSUE TITLE
add user login

### ISSUE THREAD

**Issue by Aajibolah** [tbf-challenge/teamwork-be#24]
## User Story Description

As an Admin/employee,
I need a login page,
So I can sign in.

## Steps to Follow (optional)

-   [ ] Enter Email
-   [ ] Enter Password
-   [ ] Additional steps as necessary

## Acceptance criteria
- Frontend
- [ ] A login page should be created
- [ ] Admin should be able to sign in with email and password
- [ ] The credentials for signing in should be valid
- Backend
- [ ] A login endpoint should be created -  POST /auth/signin
- [ ] The endpoint should accept email and password
- [ ] A database should be created - chore

## Additional Considerations

Any supplemental information including unresolved questions links to external resources, screenshots, etc.

TASKS
- [ ]  Add user login endpoint (Backend) - https://github.com/tbf-challenge/teamwork-be/issues/40
- [ ]  Add user login template (Frontend) - https://github.com/tbf-challenge/teamwork-be/issues/41
- [ ]  Add jwt - https://github.com/tbf-challenge/teamwork-be/issues/42
