### ISSUE TITLE
add tests to untested endpoints and services

### ISSUE THREAD

**Issue by jocrah** [tbf-challenge/teamwork-be#243]
## Description
At the time testing was introduced to the code, we had already shipped some endpoints along with their services.

This is being created as a large task which will be broken down into the tasks outlined below

## Tasks for 8th Milestone

-  [x] - User sign in endpoint
-  [x] -  Invite user endpoint
-  [x] #275
-  [x] - https://github.com/tbf-challenge/teamwork-be/issues/264
-  [x] - https://github.com/tbf-challenge/teamwork-be/issues/262
-  [x] - update article endpoint

**Comment by jocrah** [comment]
**NB: This issue isn't meant for assignment to a single person. When you pick one of them, create a subtask and link it next to the task in the issue description.** 

If possible also comment on this same issue about the one you've picked up.

This is to prevent us from tripping over each other and spending time on the same task.

**Comment by beblicarl** [comment]
1. I , Senior man Carl Bebli, has picked the `create article endpoint` testing

**Comment by beblicarl** [comment]
2. I am working on the get tags testing

**Comment by beblicarl** [comment]
3. I am working on the `update article endpoint testing`

**Comment by beblicarl** [comment]
4. I am working on the `user signin endpoint testing`

**Comment by beblicarl** [comment]
5. I am working on the `invite-user endpoint` test

**Comment by beblicarl** [comment]
6. I am working on the `get user invite information` endpoint
