### ISSUE TITLE
Admin should be able to create employee account

### ISSUE THREAD

**Issue by Derayoo** [tbf-challenge/teamwork-be#25]
## User Story Description

As an Admin,
I want to be able to create an employee account
So I can setup an account for a new employeeemployee.

## Steps to Follow (optional)

-   [ ] Step #1
-   [ ] Step #2
-   [ ] Additional steps as necessary

## Acceptance criteria

Frontend
Admin should be able to add a new employee account
Admin should be able to remove employee account 
Backend
An employee account should be created - POST /auth/create-user
The endpoint should accept the payload 
I. first Name
ii. last Name
iii. Email
Iv. password
v. gender
vi. jobrole
vii. department
viii. Address
The password should be autogenerated

## Additional Considerations

Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

## Sprint Ready Checklist

1.  - [ ] Acceptance criteria defined
2.  - [ ] Team understands acceptance criteria
3.  - [ ] Team has defined solution / steps to satisfy acceptance criteria
4.  - [ ] Acceptance criteria is verifiable / testable
5.  - [ ] External / 3rd Party dependencies identified

TASKS
- [ ]  Add user creation template - https://github.com/tbf-challenge/teamwork-be/issues/43
- [ ]  Add user creation endpoint - https://github.com/tbf-challenge/teamwork-be/issues/44
