### ISSUE TITLE
user should be able to create articles

### ISSUE THREAD

**Issue by Derayoo** [tbf-challenge/teamwork-be#27]
## User Story Description

As an employee,
I want to write articles based on my topic of interest,
so I can share them with my colleagues.

As a [role]
I want to [action to be performed]
So I can [result to be achieved]

## Steps to Follow (optional)

-   [ ] Step #1
-   [ ] Step #2
-   [ ] Additional steps as necessary

## Acceptance criteria
Acceptance Criteria (FE/BE)
Employees should be able to create articles
Articles created on platform should not exceed character limit of 63,206(or less)

## Sprint Ready Checklist

1.  - [ ] Acceptance criteria defined
2.  - [ ] Team understands acceptance criteria
3.  - [ ] Team has defined solution / steps to satisfy acceptance criteria
4.  - [ ] Acceptance criteria is verifiable / testable
5.  - [ ] External / 3rd Party dependencies identified

TASKS
- [ ]  Add article creation template - https://github.com/tbf-challenge/teamwork-be/issues/46
- [ ]  Add article creation endpoint - https://github.com/tbf-challenge/teamwork-be/issues/45
