### ISSUE TITLE
Add tags to posts

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#71]
## Feature Description

Describe what the feature is intended to accomplish & why it's important
As an employee
I want to be able to view just a specific category(tag) of articles.
So I can get all the articles about my topic of interest in one place.

Acceptance Criteria
Employees should be able to select and view a selected category of articles
Limit of tags an article can be tagged with 3

## Major User Stories/tasks

-   [ ] Add endloint for tags - https://github.com/tbf-challenge/teamwork-be/issues/70
-   [ ] User Story or Task #2
-   [ ] Additional User Stories or Tasks as necessary

## Additional Considerations

Include anything else that may be helpful. For example, links to external resources.
