### ISSUE TITLE
Add functionality to enable users report offensive posts

### ISSUE THREAD

**Issue by jakazzy** [tbf-challenge/teamwork-be#72]
## Task Description

Describe the task to be completed.
Add functionality to enable users to report offensive posts

- [ ] Create report table for offensive post reports - https://github.com/tbf-challenge/teamwork-be/issues/144
- [ ] Add offensive report validation to schema.js - https://github.com/tbf-challenge/teamwork-be/issues/145
- [ ] Create an endpoint for reporting offensive posts - https://github.com/tbf-challenge/teamwork-be/issues/146

**Comment by itzgeebee** [comment]
@jakazzy Please can you help give more details on what you have in mind for this task?

**Comment by jocrah** [comment]
we have broken down the tasks in other issues so this can be closed
